### ISSUE TITLE
resize the file imported by img

### ISSUE THREAD

**Issue by Armand1** [Armand1/contour-extraction-for-R#1]
Wwhat I need in the resize part is an “if else” step that resizes to a rational size if it’s really big. I am currently dealing with an image that, after resize, 4m elements and is 31.9MB.  That’s too big to plot comfortably.  And it takes too long to import --- that's the big thing that is slowing the processing down.

So, you need to specify what a good size is (I dunno, 500x500?) and bring anything that’s really big down to that.

**Comment by LittleAri** [comment]
Default resize parameter has been set to 1 (i.e. no resize). If an image's height > 3000, resize parameter is set to 0.6 (60% of original size) and if it's > 1000, then resize = 0.8.
